lang: es

project:
  output-dir: docs

website:
  navbar:
    left:
      - href: ./pt/index.html
        text: "PT"
      - href: ./en/index.html
        text: EN  
      - href: /index.html
        text: "**ES**"    
      - text: "Principal"
        href: /index.html
      - text: Sobre LatinR
        menu:        
          - text: "Equipo Organizador"
            href: sobre/equipo/index.qmd        
          - href: sobre/apoyo/index.qmd
          - href: sobre/coc/index.qmd
          - href: sobre/ediciones-anteriores/index.qmd  
      - text: Participa
        menu: 
          - text: "Llamado a presentación de trabajos"
            href: blog/es/2023-04-24-presentacion-trabajos-2023.html
          - text: "Inscripción"
            href: https://www.eventbrite.cl/e/latinr-2023-conferencia-latinoamericana-sobre-uso-de-r-en-id-tickets-637517701607
          - text: "Costo de inscripción"
            href: blog/es/2023-06-08-inscripcion.html  
      - text: LatinR 2023
        menu: 
          - text: "Lugar"
            href: cronograma/lugar/index.qmd 
          - text: "Recursos turísticos"
            href: cronograma/recursos-turisticos/index.qmd             
          - text: "Conferencistas"
            href: cronograma/conferencistas/index.qmd
          - text: "Tutoriales"
            href: cronograma/tutoriales/index.qmd    
          - text: "Becas de asistencia"
            href: blog/es/2023-08-18-becas-2023.html               
      - text: "Novedades"
        href: blog/es/index.html          