lang: es

project:
  output-dir: docs

website:
  navbar:
    left:
      - href: ./pt/index.html
        text: "PT"
      - href: ./en/index.html
        text: EN  
      - href: /index.html
        text: "**ES**"    
      - text: "Principal"
        href: /index.html
      - text: Sobre LatinR
        menu:        
          - href: sobre/equipo/index.qmd        
          - href: sobre/apoyo/index.qmd
          - href: sobre/coc/index.qmd
          - href: sobre/ediciones-anteriores/index.qmd  
      - text: Participe
        menu: 
          - text: "Llamado a Presentación de Trabajos"
            href: blog/es/2023-04-24-presentacion-trabajos-2023.html
          - text: "Inscripción"
            href: https://www.eventbrite.cl/e/latinr-2023-conferencia-latinoamericana-sobre-uso-de-r-en-id-tickets-637517701607
          - text: "Precios de Inscripción"
            href: blog/es/2023-06-08-inscripcion.html  
      - text: LatinR 2023
        menu: 
          - text: "Conferencias"
            href: cronograma/conferencias/index.qmd
      - text: "Novedades"
        href: blog/es/index.html          