lang: pt

project:
  output-dir: docs/pt

website:
  navbar:
    left:
      - href: /index.html
        text: "**PT**"
      - href: ../en/index.html
        text: EN  
      - href: ../index.html
        text: ES      
      - text: "Página inicial"
        href: /index.html
      - text: Sobre a LatinR
        menu:        
          - href: sobre/equipo/equipe.qmd        
          - href: sobre/apoyo/apoio.qmd
          - href: sobre/coc/codigo-de-conduta.qmd
          - href: sobre/ediciones-anteriores/edicoes-anteriores.qmd     
      - text: LatinR 2023
        menu: 
          - text: "Palestras convidadas"
            href: cronograma/conferencias/palestras-convidadas.qmd          
      - text: "Novidades"
        href: blog/pt/index.html                 
      
        