lang: en

project:
  output-dir: docs/en

website:
  navbar:
    left:
      - href: ../pt/index.html
        text: "PT"
      - href: ./index.html
        text: "**EN**"  
      - href: ../index.html
        text: "ES"    
      - text: "Home"
        href: /index.html
      - text: About LatinR
        menu:        
          - href: sobre/equipo/team.qmd        
          - href: sobre/apoyo/sponsors.qmd
          - href: sobre/coc/code-of-conduct.qmd
          - href: sobre/ediciones-anteriores/previous-editions.qmd            
      - text: "News"
        href: blog/en/index.html                 