on:
  workflow_dispatch:

name: Update data from sheets


jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      TOKEN_JSON: ${{ secrets.TOKEN_JSON }}
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # add software dependencies here

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::usethis
            any::googlesheets4
            any::readr
            any::here
            
      - name: Execute Script
        run: |
          Rscript "data-raw/actions-update-from-google-sheets.R"      
          

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Update data" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
          